apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-hello-world
spec:
  selector:
    matchLabels:
      app: java-hello-world
  replicas: 2
  template:
    metadata:
      labels:
        app: java-hello-world
    spec:
      containers:
      - image: fstab/java-hello-world
        name: java-hello-world
        ports:
        - containerPort: 8080
